name: Deployment pipeline

on:
  push:
    branches:
      - master
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: superfly/flyctl-actions/setup-flyctl@master


      - name: npm install 
        run: npm install && cd ../client && npm install
        working-directory: ./server

      - name: lint
        run: npm run lint
        working-directory: ./server

      - name: test client
        run: npm run test
        working-directory: ./client
        
      - name: test server
        run: npm run test
        working-directory: ./server

      - name: build server and client
        run: npm run build:ui && npm run build
        working-directory: ./server

      - name: deploy app
        run: npm run deploy
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}